### PR TITLE
Lo-fi Hero section

### PR DESCRIPTION
**Pull request by ItsAdel**
:tickets: **Ticket(s)**: Closes #

---
## :construction_worker: Changes

Created the hero section.
Added the form to sign up to mailing list

## :flashlight: Testing Instructions
Try it out in amplify and use your browser's responsive mode to view it on a phone or tablet.

### CODE REVIEW

**Comment by kozr** [comment]
I've just noticed some minor CSS problems. 
image When focused, the highlight is covered by the button. Disabling horizontal scrolling would also be cool to avoid the white strip on the right as well.

**Comment by rmehri01** [comment]
@kozr on mine the outline looks like this:

image

**Comment by rmehri01** [comment]
Also is it just me or is there a very thin line through the B in UBC for some reason LOL

**Comment by rmehri01** [comment]
@kozr Also, the website template has issues with horizontal scrolling so all the prs have it too. I think it might need to be disabled at top level or something?

**Comment by kozr** [comment]
@rmehri01 yeah I remember dealing with this last year and I did something like x-overflow: hidden or something

**Comment by ItsAdel** [comment]
> Also is it just me or is there a very thin line through the B in UBC for some reason LOL

Yeah I think its because of the way the svg is setup. I can talk to Sandy and try to ask if they can combine it. I see it too

**Comment by ItsAdel** [comment]
> @rmehri01 yeah I remember dealing with this last year and I did something like x-overflow: hidden or something

I'll let this change be done in the overall template and not this PR then

**Pull request merged**
