### PR TITLE
Lo-fi About Section

### PR DESCRIPTION
**Pull request by michaelfromyeg**
:tickets: **Ticket(s)**: Closes n/a

---

## :construction_worker: Changes

- Added lo-fi about section: needed text, positioned, rough gradient background from an SVG. I could make it a little higher-fi as well, wasn't sure how simple to go.
- Added Source Sans Pro to `nuxt.config.js` per the Nuxt [FAQ](https://nuxtjs.org/faq/).

## :thought_balloon: Notes

- Should I add higher-q SVGs, such as the log wood titles?
- Might want to prune Google font imports from other PRs.

## :flashlight: Testing Instructions

- Run it locally, make sure it looks alright on mobile

### CODE REVIEW

**Comment by kozr** [comment]
Your commits history included my commits. Maybe you can try changing the history and cherry-pick your commits? I just learned this trick a few days ago lol.

**Comment by michaelfromyeg** [comment]
Yeah I noticed that, let me try and fix it! Do you have a link / reference for "cherry picking" commits?

**Comment by kozr** [comment]
I don't have a link. But the general idea to reset to a certain base commit, and the use `git cherry-pick <commit>` to lay down history.

e.g. What you can do is:
git reset --hard a245154cc52a308effc3bfd0724d72b702715147
git cherry-pick <commit>
git cherry-pick <commit>

**Comment by michaelfromyeg** [comment]
Well... I don't think I fixed the commit history, but that did merge in dev. I need that Git workshop!

Worth trying again? I found [this](https://medium.com/magnetis-backstage/git-basics-rewriting-a-branchs-commit-history-from-scratch-7bc966716d8b) which looks like it should be handy for doing this right

**Pull request merged**
