### PR TITLE
Add general background color

### PR DESCRIPTION
**Pull request by kozr**
## :construction_worker: Changes

A brief summary of what changes were introduced.
- Added linear background color to LHD site according to the last element on figma

### CODE REVIEW

**Comment by rmehri01** [comment]
Should we also add other top level changes in `index.vue` to this? For example the default font and the website title and logo.

**Comment by kozr** [comment]
I started work on the metadata for the website. They're on another branch. I should add the default font here though.

**Comment by rmehri01** [comment]
> I started work on metadata for the website. They're on another branch. I should add the default font here though.

Great thanks!

**Comment by rmehri01** [comment]
Since we have the default font and background colour here, should we remove them from each component later?

**Comment by michaelfromyeg** [comment]
Yeah I think this change will be super nice, since then we'll be able to use the Figma gradient as-is; I tried to approximate it on the Intro section and it was painful LOL

**Pull request merged**
