### PR TITLE
Update hackathon id

### PR DESCRIPTION
**Pull request by rmehri01**
## :construction_worker: Changes

- Updated hackathon id to 'LHD2021' to get prod working

## :thought_balloon: Notes

- Last year's repo is called LHD2020 so I guess this is LHD2021 even though its not in 2021
- Dev firebase won't work with the new hackathon id but I can update it to include LHD2021

## :flashlight: Testing Instructions

- Check out the amplify link, it should work now.

### CODE REVIEW

**Comment by kozr** [comment]
Ok something's different. when you go to preview PR, it searches for WelcomeText

**Comment by rmehri01** [comment]
@kozr I just updated the prod firebase to make it LHD2021 instead and the amplify link works now but page build still doesn't work?

**Comment by kozr** [comment]
Hmmmm what could it be

**Comment by rmehri01** [comment]
@kozr it was a setting under branch protection for the repo, I just removed it and looks like it works now.

**Comment by kozr** [comment]
Yeah I put it in as required because it sounded right haha. We should find out what it is though.

**Comment by kozr** [comment]
Looks good

**Pull request merged**
