### PR TITLE
HackCamp rebrand

### PR DESCRIPTION
**Pull request by michaelfromyeg**
:tickets: **Ticket(s)**: Closes n/a

---

## :construction_worker: Changes

* Rebrand to HackCamp: update [copy text](https://www.notion.so/nwplus/copy-text-04d43b20d2bd4a3d9aa54ea589e8884b) change SVGs
* Fixed new sizing issues introduced

## :thought_balloon: Notes

* I changed almost all references to LHD but we may want to rollback a few? Not sure how much we wanted to change internally (if anything)

## :flashlight: Testing Instructions

Check out the Amplify link!

### CODE REVIEW

**Review by rmehri01 — COMMENTED** [review]
For some reason I think this part of the background is over the title for me?

image

**Review by rmehri01 — COMMENTED** [review]
Also does the copyright in the footer text need to change?

**Comment by rmehri01** [comment]
Is this supposed to still say LHD?

image

**Comment by kozr** [comment]
Footer also says LHD

**Comment by jackyzha0** [comment]
> For some reason I think this part of the background is over the title for me?
> 
> image

I think that's the fireflies but yeah I see that too

**Comment by kozr** [comment]
Favicon needs a change too? It might take a couple more days for design so we will worry about that next PR.

**Comment by jackyzha0** [comment]
> Favicon needs a change too? It might take a couple more days for design so we will worry about that next PR.

philman is whipping that up rn, should be ready in the next little bit

**Review by rmehri01 — APPROVED** [review]
Looks good chief 🚀

**Review by kozr — APPROVED** [review]
LGTM! Thanks a ton.

**Comment by rmehri01** [comment]
Umm also for some reason the about nav sign doesnt work for me anymore? FAQ and sponsors still are though.

**Comment by michaelfromyeg** [comment]
OH yo that is definitely because of the z-index changes, I made it so that the stars hide behind the logo but I might've broken that. Lemme fix it rq!

**Comment by michaelfromyeg** [comment]
wait jk it works for me LOL that's weird

**Review by jackyzha0 — APPROVED** [review]
l g t m 🏕️

**Comment by rmehri01** [comment]
Nice, looks like it works now!

**Pull request merged**
